import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Multi steps form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`bg-blue-100 min-h-screen flex`}>
        <div className={`bg-white max-w-max m-auto grid grid-flow-col rounded-xl`}>
          <div className={`bg-blue-400 rounded-br-3xl rounded-tr-3xl p-6 pr-20 flex flex-col gap-4`}>
            <div className={`flex flex-row items-center gap-3`}>
              <div class="w-6 h-6 rounded-full border border-blue-50 flex justify-center items-center">
                <p className={`text-blue-50 font-semibold text-xs`}>1</p>
              </div>{" "}
              <div>
                <div className={`text-xs text-white`}>STEP 1</div>
                <div className={`text-sm text-white font-semibold`}>YOUR INFO</div>
              </div>
            </div>
            <div className={`flex flex-row items-center gap-3`}>
              <div class="w-6 h-6 rounded-full border border-blue-50 flex justify-center items-center">
                <p className={`text-blue-50 font-semibold text-xs`}>2</p>
              </div>{" "}
              <div>
                <div className={`text-xs text-white`}>STEP 2</div>
                <div className={`text-sm text-white font-semibold`}>SELECT PLAN</div>
              </div>
            </div>{" "}
            <div className={`flex flex-row items-center gap-3`}>
              <div class="w-6 h-6 rounded-full border border-blue-50 flex justify-center items-center">
                <p className={`text-blue-50 font-semibold text-xs`}>3</p>
              </div>
              <div>
                <div className={`text-xs text-white`}>STEP 3</div>
                <div className={`text-sm text-white font-semibold`}>ADD-ONS</div>
              </div>
            </div>{" "}
            <div className={`flex flex-row items-center gap-3`}>
              <div class="w-6 h-6 rounded-full border border-blue-50 flex justify-center items-center">
                <p className={`text-blue-50 font-semibold text-xs`}>4</p>
              </div>{" "}
              <div>
                <div className={`text-xs text-white`}>STEP 4</div>
                <div className={`text-sm text-white font-semibold`}>SUMMARY</div>
              </div>
            </div>
          </div>
          <div className={`px-20 py-12`}>
            <div>
              <h3 className={`text-3xl font-semibold`}>Personal info</h3>
              <h5 className={`text-sm font-light`}>Please provide your name, email address, and phone number</h5>
            </div>
            <div className="mt-10">
              <form className="flex flex-col" action="">
                <label htmlFor="Name" className={`font-semibold text-gray-900 text-sm`}>
                  Name
                </label>
                <input type="text" name="" className={`border border-gray-200 rounded-md mb-5`} />
                <label htmlFor="Email address" className={`font-semibold text-gray-900 text-sm`}>
                  Email address
                </label>
                <input type="text" name="" className={`border border-gray-200 rounded-md mb-5`} />
                <label htmlFor="Phone Number" className={`font-semibold text-gray-900 text-sm`}>
                  Phone Number
                </label>
                <input type="text" className={`border border-gray-200 rounded-md mb-5`} />
                <input type="submit" value="Next step" className={`bg-blue-900 max-w-min text-white self-end mt-10 text-sm font-semibold px-4 py-2 rounded-md`} />
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
